"""add_database_name_to_database_configs

Revision ID: 56dc71826e48
Revises: 001_initial
Create Date: 2026-07-19 00:28:42.847362
"""

from alembic import op
import sqlalchemy as sa


revision = '56dc71826e48'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('database_configs', sa.Column('database_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('database_configs', 'database_name')
    # ### end Alembic commands ###
